kind: pipeline
type: docker
name: default

workspace:
  base: /go
  path: src/github.com/JustSomeHack/${DRONE_REPO_NAME}

trigger:
  event:
    - push
    - pull_request
    - tag
    
steps:
  - name: test
    image: golang:latest
    commands:
      - go test -coverprofile=coverage.txt ./...

  - name: build
    image: golang:latest
    environment:
      CGO_ENABLED: "0"
      GOOS: linux
      GOARCH: amd64
    commands:
      - go build -v -a -ldflags "-X main.version=build.${DRONE_BUILD_NUMBER}" -o build/docker/ci-kubernetes

  # - name: docker
  #   image: plugins/docker
